name: Test CI
on:
  pull_request:
  push:
    branches:
      - '!main'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install deps
        run: bun i

      - name: lint
        run: bun run test